# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppDemo

  pod 'AFNetworking', '~> 2.6'
  pod 'Masonry'

  target 'AppDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppDemoUITests' do
    # Pods for testing
  end

end
